# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19D-S65uOr8dl1cx19x0AZwX9wnrZo-fW
"""

import matplotlib.pyplot as plt
import numpy as np
x= np.array([1,2,6,8])
y= np.array([3,8,1,10])
plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
t = np.linspace(0, 2, 1000)
pulse = np.sin(2 * np.pi * 1.5 * t) * np.exp(-0.8 * t)
pulse += 0.5 * np.sin(2 * np.pi * 8 * t) * np.exp(-1.5 * t)
pulse = np.abs(pulse) * np.sin(4 * np.pi * t)
plt.figure(figsize=(10, 4))
plt.plot(t, pulse, color="red", label="Yurak pulsining modeli")
plt.title("Yurak Pulsining Simulyatsiyasi")
plt.xlabel("Vaqt (soniya)")
plt.ylabel("Amplitude")
plt.grid()
plt.legend()
plt.show()

import matplotlib.pyplot as plt
import numpy as np
n_points = 5
radius_outer = 1
radius_inner = 0.5
angles = np.linspace(0, 2 * np.pi, 2 * n_points + 1)
radii = np.array([radius_outer if i % 2 == 0 else radius_inner for i in range(len(angles))])
x = radii * np.cos(angles)
y = radii * np.sin(angles)
plt.figure(figsize=(6, 6))
plt.plot(x, y, color="blue", linewidth=2, label="Yulduz")
plt.fill(x, y, color="lightblue", alpha=0.5)
plt.title("Yulduz shakli")
plt.xlabel("X koordinatasi")
plt.ylabel("Y koordinatasi")
plt.axhline(0, color='black', linewidth=0.5, linestyle="--")
plt.axvline(0, color='black', linewidth=0.5, linestyle="--")
plt.grid()
plt.legend()
plt.axis("equal")
plt.show()

import matplotlib.pyplot as plt
import numpy as np

y= np.array([3,8,1,10])
plt.plot(y, marker='o', ms=20, mec='r')
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x1= np.array([0,1,2,3])
y1= np.array([3,8,1,10])
x2= np.array([0,1,2,3])
y2= np.array([6,2,7,11])
plt.plot(x1,y1,x2,y2)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x= np.array([0,1,2,3,4,5])
y= np.array([0,8,12,20,26,38])
plt.scatter(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x= np.array([0,1,2,3,4,5])
y= np.array([0,2,8,1,14,7])
plt.scatter(x,y,color="red")

x= np.array([12,6,8,11,8,3])
y= np.array([5,6,3,7,17,19])
plt.scatter(x,y,color="green")
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x= np.array([0,1,2,3,4,5])
y= np.array([0,2,8,1,14,7])
mycolor=["red","green","purple","lime","aqua","yellow"]
plt.scatter(x,y,color="red")
plt.scatter(x,y,color=mycolor)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x= np.array([0,1,2,3,4,5])
y= np.array([0,2,8,1,14,7])
mycolor=["red","green","purple","lime","aqua","yellow"]
plt.scatter(x,y,color="red")
size=[10,60,120,80,20,190]
plt.scatter(x,y,color=mycolor, s=size)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x= np.array(["A","B","C","D"])
y= np.array([3,8,1,10])
plt.bar(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x= np.array(["A","B","C","D"])
y= np.array([3,8,1,10])
plt.barh(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x= np.array([35,25,25,15])

plt.pie(y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x= np.array([35,25,25,15])
mylabels = ["Apples", "Bananas", "Cherries", "Dates"]
plt.pie(y, labels=mylabels)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x= np.array([35,25,25,15])
mylabels = ["Apples", "Bananas", "Cherries", "Dates"]
myexplode = [0.2, 0, 0, 0]
plt.pie(y, labels=mylabels, startangle=90, explode=myexplode)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x= np.array([35,25,25,15])
mylabels = ["Apples", "Bananas", "Cherries", "Dates"]
mycolors = ["black", "hotpink", "b", "#4CAF50"]
myexplode = [0.2, 0, 0, 0]
plt.pie(y, labels=mylabels, startangle=90, explode=myexplode, colors=mycolors)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x= np.array([35,25,25,15])
mylabels = ["Apples", "Bananas", "Cherries", "Dates"]
plt.pie(y, labels=mylabels)
plt.legend()
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x= np.array([35,25,25,15])
mylabels = ["Apples", "Bananas", "Cherries", "Dates"]
plt.pie(y, labels=mylabels)
plt.legend(title="Four Fruits:")
plt.show()

import matplotlib.pyplot as plt
import numpy as np
from matplotlib import cm
plt.style.use('_mpl-gallery')
#Make data
X = np.arange(-5, 5, 0.25)
Y = np.arange(-5, 5, 0.25)
X, Y = np.meshgrid(X, Y)
R = np.sqrt(X**2 + Y**2)
Z= np.sin(R) #
# Plot the surface
fig, ax = plt.subplots(subplot_kw={"projection": "3d"})
ax.plot_surface (X, Y, Z, vmin=Z.min() * 2, cmap=cm.Blues)
ax.set(xticklabels=[],
yticklabels=[],
zticklabels=[])
plt.show()